# wrangler.toml
name = "jelvan-blogs"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "blogs-jelvan"
database_id = "0de1a493-152d-446d-a7da-646aeeaa855f"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "jelvan-blogs-media"
