# wrangler.toml
name = "jelvan-blogs"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "jelvan-blogs-db"
database_id = "PASTE_YOUR_COPIED_D1_DATABASE_ID_HERE"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "jelvan-blogs-media"
